//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNS_Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fulfill
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string ProCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> SKU { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> Supplied { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Order Order1 { get; set; }
    }
}
